---
deployment:
  tasks:
    - export DEPLOYPATH=/home/monaksof/public_html
    - /bin/cp -R /home/monaksof/repositories/verityDeploy/* $DEPLOYPATH
    - cd $DEPLOYPATH
    - /bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
